### ISSUE TITLE
Captcha server

### ISSUE THREAD

**Issue by DevilLord41** [byte-0x74/PlutoniumPrivate#1]
Hi, i would like to know what captcha solving method you used.

**Comment by byte-0x74** [comment]
I used GrowX's api to solve the puzzle but ig its no more public.

**Comment by BirdyTheDev** [comment]
> Hi, i would like to know what captcha solving method you used.

https://github.com/byte-0x74/puzzle-solver U Can Use This Public Solver By Byte-0x74
